import {
  TrendingUp,
  Droplets,
  Flame,
  Gift,
  ChartCandlestick,
  Hourglass,
  HandCoins,
  CalendarClock,
  Handshake,
} from "lucide-react";
import { PointCard } from "../fragments/PointCard";

export default function HowPointsWorkTab() {
  return (
    <div className="space-y-6">
      <PointCard
        title="Trading points"
        icon={<TrendingUp className="w-5 h-5 text-blue-900" />}
        color="blue"
        steps={[
          { label: "Open position", value: <ChartCandlestick /> },
          { label: "Hold & manage", value: <Hourglass /> },
          { label: "Close position", done: true },
        ]}
        description="Points are earned when you close a leveraged position. The amount depends on position size, time held, and outcome."
      />

      <PointCard
        title="Liquidity points"
        icon={<Droplets className="w-5 h-5 text-violet-600" />}
        color="violet"
        steps={[
          { label: "Deposit USDC", value: <HandCoins /> },
          { label: "Daily tracking", value: <CalendarClock /> },
          { label: "Points accrue", done: true },
        ]}
        description="Calculated from your average daily USDC balance in the pool. Larger deposits and longer duration result in more points."
      />

      <PointCard
        title="Loyalty multiplier"
        icon={<Flame className="w-5 h-5 text-violet-600" />}
        color="violet"
        steps={[
          { label: "Week 1", value: "1.0×" },
          { label: "Week 4", value: "1.2×" },
          { label: "Week 12", value: "1.5×", done: true },
        ]}
        description="Applied to liquidity points only. Your multiplier grows over time while providing liquidity without full withdrawal. Partial withdrawals reduce it proportionally."
        note="Multiplier values are illustrative and may change over time."
      />

      <PointCard
        title="Referral points"
        icon={<Gift className="w-5 h-5 text-green-600" />}
        color="green"
        steps={[
          { label: "Referred user earns", value: "100" },
          { label: "Attribution (25%)", value: <Handshake /> },
          { label: "You receive", value: "25", done: true },
        ]}
        description="Earn a percentage of the points generated by users you invite. Referral rewards are calculated automatically based on the activity of your referrals."
        note="Referral percentage values are illustrative and may change over time."
      />
    </div>
  );
}
