import { ActorCard } from "../fragments/ActorCard";

export default function PointsSection() {
  return (
    <section
      className="
        w-full py-28 px-6
        bg-linear-to-b from-[#BFD1FF] via-[#DCE5FF] to-[#C8D6FF]
        flex flex-col items-center text-center
      "
    >
      {/* Title */}
      <h2 className="text-5xl font-semibold text-[#00246B] mb-5">
        2xSwap Points Program
      </h2>

      {/* Subtitle */}
      <p className="max-w-xl text-[#4A64A8] mb-10 leading-relaxed">
        The 2xSwap Points Program rewards early real users and long-term
        supporters. Points are distributed in ongoing seasons as the protocol
        evolves.
      </p>

      {/* Section Label */}
      <p className="text-lg font-bold text-[#00246B] mb-12">
        Each week a fixed amount of points is distributed to:
      </p>

      {/* Cards */}
      <div className="flex flex-col md:flex-row gap-10 mb-14">
        <ActorCard
          title="Traders (A)"
          description="Based on traded volume and profit, with smaller rewards for honest losing positions."
        />

        <ActorCard
          title="Liquidity providers (B)"
          description="Based on how much they deposit and how long they stay in the pool. Early users receive a multiplier."
        />
      </div>

      {/* Footer Notes */}
      <div className="max-w-3xl text-sm text-[#3F5FA8] leading-relaxed">
        <p className="font-semibold">
          Referrals earn 25% of the points generated by invited users, with caps
          to keep distribution fair.
        </p>
        <p className="font-bold">
          Point mechanics may evolve over time to prevent abuse and ensure fair
          distribution.
        </p>
      </div>
    </section>
  );
}
